In [7]:
import numpy as np


In [9]:
matrix_a = np.arange(9, dtype=float).reshape(3, 3)
print("Matrix 'matrix_a':")
print(matrix_a)

Matrix 'matrix_a':
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [10]:
array_b = np.array([10, 10, 10])
print("\nArray 'array_b':")
print(array_b)


Array 'array_b':
[10 10 10]


In [ ]:
print("\nElement-wise addition of 'matrix_a' and 'array_b':")
print(np.add(matrix_a, array_b))

In [ ]:
print("\nElement-wise substaction of 'matrix_a' and 'array_b':")
print(np.subtract(matrix_a, array_b))

In [ ]:
print("\nElement-wise multiplication of 'matrix_a' and 'array_b':")
print(np.multiply(matrix_a, array_b))

In [ ]:
print("\nElement-wise division of 'matrix_a' and 'array_b':")
print(np.divide(matrix_a, array_b))